name = "Optics_in_the_length_gauge"
uuid = "0ea70cc5-a76f-4e09-b9f9-a74b5f0b413f"
authors = ["fernando penaranda"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
